version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'airbnb'
      MYSQL_USER: 'puc'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
